### ISSUE TITLE
ARM9MemoryBus::UpdateMemoryMap tries to access invalid memory

### ISSUE THREAD

**Issue by raphasanori** [fleroviux/Duality#22]
The sequence of events is:

1. ARM9MemoryBus constructor
2. UpdateMemoryMap(0, 0x100000000ULL);
3. [case 0x06: table[index] = VisitVRAMByAddress<GetUnsafePointerFunctor<u8>>(address);](https://github.com/fleroviux/Duality/blob/0fdef3851752d7185bfbf56d903dccca7d6c853d/src/core/src/arm9/bus.cpp#L82)
4. GetUnsafePointerFunctor
5. GetUnsafePointer

At the first attempt to read an address above the 0x068A3FFF mark (VRAM 656KB limit) everything blows up.
Could fix it checking before calling VisitVRAMByAddress:

```C++      
case 0x06: {
if ((address & 0xFFFFF) < 0xa4000) //Check
table[index] = VisitVRAMByAddress<GetUnsafePointerFunctor<u8>>(address);
break;
}
```

But for current lack of whole design complete understanding and fleroviux intentions, I'm just documenting here and not opening a pull request.

Tested on:

Platform: Win10
Compiler: Clang 11 under MSVCRT (MSVC can't handle the metaprogramming and won't build, at least in the current stable 14.29) 
(logically should be an issue in other platforms, _logically_)

**Comment by fleroviux** [comment]
Can you confirm that this is fixed as of the latest commit https://github.com/fleroviux/Duality/commit/094361cf6080cee7b126e959120268575a917e56?

The problem was in the `vram.hpp` file, it defined LCDC VRAM as a region with 41 pages but mask is 63. 
This correctly models the mirroring behavior of LCDC VRAM but the `Region` class template didn't account for the `mask >= number of pages` case. To avoid a branch I just made the LCDC region 64 pages large, which is still correct, just slightly more wasteful.

**Comment by raphasanori** [comment]
I knew you would come with a better solution ヾ(≧▽≦*)o
Merged upstream and now works without a flaw! Now it can compile and run without problems under clang+Visual Studio on Windows.
