### ISSUE TITLE
[SDL Frontend] APU Destructor trying to call invalid memory

### ISSUE THREAD

**Issue by raphasanori** [fleroviux/Duality#23]
The sequence of events is:

1. Everything out of scope
2. ~Core
3. ~CoreImpl
4. ~Interconnect
5. ~APU

~APU tries to call close on its audio device, but apparently the check for null pointer doesn't help, because despite having an address it's invalid memory since sometime in the recent past(?). So the application crashes trying to access invalid memory.

Since Interconnect it's marked to be [extinguished from existence](https://github.com/fleroviux/Duality/blob/0fdef3851752d7185bfbf56d903dccca7d6c853d/src/core/src/interconnect.hpp#L28), this rework could fix the destruction order and solve this issue.

Can't really suggest a solution, for currently lacking understanding of the whole program structure.

Tested on:

Platform: Win10
Compiler: Clang 11 under MSVCRT (Tests can only be performed after fixing #22, otherwise won't run)

**Comment by MerryMage** [comment]
AudioDevice is destroyed before Core, thus it becomes invalid during destruction. See [main.cpp](https://github.com/fleroviux/Duality/blob/0fdef3851752d7185bfbf56d903dccca7d6c853d/src/duality-sdl/src/main.cpp). 

`SDL2AudioDevice` is constructed and destructed in `loop`, whereas `Core` is constructed and destructed in `main`.

A likely simple fix would be to construct `Core` on line 40 instead, so that the destruction order is correct.

**Comment by fleroviux** [comment]
Thanks! Fixed in https://github.com/fleroviux/Duality/commit/83a9dfb4944b475cdfb9715636342c30bfc06750
